### ISSUE TITLE
Widgets in declarative UI should support common properties

### ISSUE THREAD

**Issue by cmeyer** [nion-software/nionui#15]
* enable/disable
* visible/hidden flags

**Comment by Brow71189** [comment]
I think there are some more flags that all widgets should have:
- stylesheet
- width, height, min-width, min-height, max-width, max-height
- tool-tip
and maybe others, but those are the ones I'm usually missing

**Comment by cmeyer** [comment]
> * stylesheet

Did you have something in mind for a stylesheet? Do you mean CSS that somehow focuses on that element only? (this would be problematic since the element isn't guaranteed to be an HTML style element).

**Comment by Brow71189** [comment]
I thought about the stylesheet that you can set for widgets in the
old-style UI. I guess it comes from qt but it looks like CSS

Chris Meyer <notifications@github.com> schrieb am Do., 10. Okt. 2019, 18:48:

**Comment by Brow71189** [comment]
One more thought on this: We shouls also define which of these properties need to be bindable.
I would suggest at least enable, visible and tool-tip.

**Comment by cmeyer** [comment]
Fixed 9594bfc36224ac6510dc0e93c1e0a989a1d3bc49

No stylesheet.
