### ISSUE TITLE
"map_to_global" returns wrong screen coordinates on monitors with dpi other than 96/72

### ISSUE THREAD

**Issue by Brow71189** [nion-software/nionui#42]
This is the function which gets the widget's position and calculates the screen coordinates according to the screen dpi:
https://github.com/nion-software/nionui/blob/604a1ce312abbd5e391e1ff15593d3f679046509/nion/ui/PyQtProxy.py#L3944

Depending on the actual dpi of your monitor, this reports wrong values, because the screen dpi is hardcoded in this function:
https://github.com/nion-software/nionui/blob/604a1ce312abbd5e391e1ff15593d3f679046509/nion/ui/PyQtProxy.py#L123

On my monitor (3840 x 2160 pixel, 144 dpi) all reported values are wrong by a factor of 1.5 which is exactly 144 / 96 (i.e. real dpi divided by hardcoded dpi).

There are a bunch of ways to get the screen dpi in python listed in this thread: https://stackoverflow.com/questions/54271887/calculate-screen-dpi
Some of them are platform-specific, but there is one that involves qt, which could be useful for us: https://stackoverflow.com/a/54273855

**Comment by cmeyer** [comment]
`GetDisplayScaling` is intended to return the display scaling relative to what Swift expects it to be and I think it is working as intended.

What is the actual end-user problem that you're seeing? And what platform?

**Comment by Brow71189** [comment]
Maybe `GetDisplayScaling` is working as intended and the bug in `map_to_global` lies somewhere else. But `map_to_global` is definitely not working as intended.

The end-user problem is that with our newest AS2 feature that allows us to open popup boxes for adjusting controls via an API call we need to pass the screen coordinates where to show the popoup. Now the usual way to trigger a popup showing is to have for example a button "Adjust" that, when the user clicks it shows the popup window. And of course the popup window should then show up in the position of this button and not at some random place on the screen.
This means we need to get the screen coordinates of the `PushButtonWidget` so that we can pass them to the API call that opens the popup window. Looking at the Qt documentation, the function `map_to_global` is supposed to do exactly this: Transform widget coordinates to global screen coordinates. Since our Qt wrapper (`QtUserInterface/PyQtProxy`) also provides this function I think this is the right one to use here. So calling `map_to_global(0, 0)` should give the global screen coordinates of the top-left corner of the widget your calling this function on.
Now when I do this on my machine which has a 144 dpi monitor, all coordinates returned are wrong by a factor of 1.5, which happens to be 144 / 96 and that made me suspicious that hardcoding 96 or 72 dpi (for Mac) could be problematic.

It is of course possible that the hardcoded dpi is not the problem, but `map_to_global` is definitely no doing the right thing. Also from my understanding the Qt function should already return the correct global screen coordinates, so I don't understand why these coordinates are scaled again here:
https://github.com/nion-software/nionui/blob/604a1ce312abbd5e391e1ff15593d3f679046509/nion/ui/PyQtProxy.py#L3950

**Comment by cmeyer** [comment]
all coordinates as treated as if they are 96-dpi (Windows/Linux) or 72-dpi (macOS) scaled. This allows all application coordinates to be blissfully unaware of the screen scaling that occurs when Windows users set their Display > Scaling & Layout to something other than 100%. On macOS, this is already the default behavior.

However, when using coordinates in other programs, you need to convert to the coordinates of the other program. In this case, it sounds like multiplying by display scaling will do the trick.

See also:

- https://docs.microsoft.com/en-us/previous-versions/windows/desktop/ms701681(v=vs.85)
- https://doc.qt.io/qt-5/scalability.html
- nion-software/nionswift#550 font issue on multiple monitors
- nion-software/nionswift#475 font scaling issues

**Comment by Brow71189** [comment]
I think we solved this one. Closing.
