### ISSUE TITLE
Add some simple operators for ``@binding``'s values

### ISSUE THREAD

**Issue by Brow71189** [nion-software/nionui#52]
I often find myself in a situation where I have a certain boolean flag available in the UI handler already, but some UI element needs the inverted flag or a combination of two (or more). In these situations it would be very useful to be able to use some (boolean) operators in the definition of a binding.

Here is an example with the current implementation:

```python
# Each combination or negation of a flag needs its own full implementation:

class UIHandler:

    @property
    def flag_1(self): ...

    @property
    def flag_2(self): ...

    @property
    def not_flag_2(self): ...

    @property
    def flag_1_and_flag_2(self): ...

# UI implementation:

ui.create_push_button(enabled='@binding(flag_1)')
ui.create_push_button(enabled='@binding(flag_2)')
ui.create_push_button(enabled='@binding(not_flag_2)')
ui.create_push_button(enabled='@binding(flag_1_and_flag_2)')
```

If we could use some operators in the binding's definition, the handler implementation would get a lot shorter:

```python
class UIHandler:

    @property
    def flag_1(self): ...

    @property
    def flag_2(self): ...

# UI implementation:

ui.create_push_button(enabled='@binding(flag_1)')
ui.create_push_button(enabled='@binding(flag_2)')
ui.create_push_button(enabled='@binding(not flag_2)')
ui.create_push_button(enabled='@binding(flag_1 and flag_2)')
```

I'm not sure if parsing the logical python operators (``not, and, or``) is feasible here, but I think also the bitwise operators would do for this purpose (``~, &, |``).

**Comment by Brow71189** [comment]
Ok I see. I'd still prefer to be able to use some operators directly since creating converters takes about as much code as implementing the properties.
But I guess this can be closed then.

**Comment by cmeyer** [comment]
I'm not completely opposed to the idea - but I'd view it as a long term goal. It's not trivial since it typically changes a binding to be read only. In any case, here's another link with some other ideas for the future:

https://www.codeproject.com/Articles/1253153/Expression-bindings-in-XAML
